import React from "react";
import Navbar from "react-bootstrap/Navbar";
import Nav from "react-bootstrap/Nav";
import Modal from "react-bootstrap/Modal";
import Container from "react-bootstrap/Container";
import Button from "react-bootstrap/Button"

class TitleBar extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            aboutShow: false,
            instShow: false
        }

        this.handleAboutShow = this.handleAboutShow.bind(this);
        this.handleAboutClose = this.handleAboutClose.bind(this);
        this.handleInstShow = this.handleInstShow.bind(this);
        this.handleInstClose = this.handleInstClose.bind(this);
    }

    handleAboutShow() {
        this.setState({aboutShow: true});
    }

    handleAboutClose() {
        this.setState({aboutShow: false});
    }

    handleInstShow() {
        this.setState({instShow: true});
    }

    handleInstClose() {
        this.setState({instShow: false});
    }

    render() {
        return(
            <Navbar bg="title" expand="lg" variant="dark" fixed="top">
                <Container fluid>
                    <Navbar.Brand href="/">Radeon Charts</Navbar.Brand>
                    <Navbar.Toggle aria-controls="basic-navbar-nav" />
                    <Navbar.Collapse id="basic-navbar-nav">
                        <Nav className="me-auto">
                            <Nav.Link onClick={this.handleAboutShow} href="#">About</Nav.Link>
                            <Nav.Link onClick={this.handleInstShow} href="#">Instructions</Nav.Link>
                        </Nav>
                    </Navbar.Collapse>

                    <Modal size="lg" show={this.state.aboutShow} onHide={this.handleAboutClose} centered className="my-modal">
                        <Modal.Header  closeButton>
                            <Modal.Title >About</Modal.Title>
                        </Modal.Header>
                        <Modal.Body>
                            Radeon Charts allows you to visualize the performance logs generated by AMD's Radeon Software Adrenalin drivers for AMD GPUs.
                            <br></br><br></br>
                                The source code can be found at &nbsp;
                            <a href="https://github.com/RobertToh/radeon-charts" target="_blank">
                                https://github.com/RobertToh/radeon-charts
                            </a>
                        </Modal.Body>
                        <Modal.Footer>
                            <Button variant="outline-light" onClick={this.handleAboutClose}>
                                Close
                            </Button>
                        </Modal.Footer>
                    </Modal>

                    <Modal size="lg" show={this.state.instShow} onHide={this.handleInstClose} centered className="my-modal">
                        <Modal.Header closeButton>
                            <Modal.Title >Instructions</Modal.Title>
                        </Modal.Header>
                        <Modal.Body>
                            Radeon Charts requires an AMD GPU running AMD's Radeon Software Adrenalin drivers. With the drivers, head to the <em>Performance</em> tab 
                            and under <em>Metrics</em> you will be able to start logging data. The data is outputted as a <code>.csv file</code>, which you simply upload to this site.
                            An example file is provided below. 
                            <br></br><br></br>
                            <a href="https://www.dropbox.com/s/318y8pkkzk5ccg6/example.CSV?dl=1" target="_blank">
                                Example CSV Here
                            </a>
                        </Modal.Body>
                        <Modal.Footer>
                            <Button variant="outline-light" onClick={this.handleInstClose}>
                                Close
                            </Button>
                        </Modal.Footer>
                    </Modal>

                </Container>
            </Navbar>
        )
    }
}

export default TitleBar;
